config/routes.rb
I18nWebOrganizer::Application.routes.draw do
  root to: 'projects#index'

  resources :projects, :except => [:show, :edit, :update] do
    resources :properties, :only => [:index]
    resources :translations, :only => [:index]
  end

  match 'projects/:project_id/properties'  => 'properties#update', via: :post
  match 'projects/:project_id/properties/add_language'  => 'properties#add_language', as: 'update_project_properties', via: :post

  match 'projects/:project_id/translations/load'  => 'translations#load', via: :post, as: :load_project_translations

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :directory

  # ---------------------------------------------------------------------------------------
  validates                 :directory, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  include ProjectsHelper

  # ---------------------------------------------------------------------------------------
  def index
    @projects = Project.all
    @project_properties = get_projects_properties(@projects)

    respond_to do |format|
      format.html # index.html.erb
    end
  end


  # ---------------------------------------------------------------------------------------
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end


  # ---------------------------------------------------------------------------------------
  def create
    # Normalize
    if params[:project] and params[:project][:directory] then
      params[:project][:directory] = params[:project][:directory] + '/' unless params[:project][:directory][-1] == '/'
    end

    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end


  # ---------------------------------------------------------------------------------------
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
    end
  end


end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  include ProjectsHelper
  include PropertiesHelper
  before_filter :get_project_and_properties!

  # ---------------------------------------------------------------------------------------
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.js # index.js.erb
    end
  end


  # ---------------------------------------------------------------------------------------
  def update
    # Update the content of the configuration.
    @project_property[:name] = params[:property][:name]
    @project_property[:default_language] = params[:property][:default_language]

    # Write it.
    update_config(@project, @project_property)

    # And redirect.
    redirect_to projects_path
  end


  # ---------------------------------------------------------------------------------------
  def add_language

    # Check the parameter
    unless params[:language] then
      json_response([422])
      return
    end

    unless I18n.t('language.' + params[:language]) then
      json_response([422])
      return
    end

    # OK, add the new language now to the list and update the config file.
    @project_property[:languages] = [] unless @project_property[:languages]
    @project_property[:languages].push(params[:language])
    update_config(@project, @project_property)

    json_response([200])
  end

end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController

  include TranslationsHelper
  include ProjectsHelper
  before_filter :get_project_and_properties!

  # ---------------------------------------------------------------------------------------
  def index
    # Build the configuration hash for the view.
    @translation_config = Hash.new

    # The current path
    @translation_config[:current_path] = '/'

    # An array of all (sub-) directories within the project's path.
    # We remove the project's path itself and the trailing '/' in the map code.
    @translation_config[:available_paths] = Dir.glob(@project.directory + "**/*/").map { |dir| dir[@project.directory.length..dir.length-2] }

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end


  # ---------------------------------------------------------------------------------------
  def load
    json_response([200, [params[:directory]]])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # ---------------------------------------------------------------------------------------
  def json_response(code)
    respond_to do |format|
      format.json { render :json => code }
    end
  end


end

app/helpers/projects_helper.rb
require "yaml"

module ProjectsHelper

  # Fetches the project from the ID in the url.
  # Throws an error, if there is no one.
  # ---------------------------------------------------------------------------------------
  def get_project_and_properties!
    raise 'No :project_id is given in the URL.' unless params[:project_id]

    @project = Project.where('id = ?', params[:project_id]).first
    raise 'No such project does exists for the given :project_id in the URL.' unless @project
    raise 'No such project directory does exists for the given :project_id: ' + @project.directory unless Dir.exists?(@project.directory)

    @project_property = get_project_properties(@project)
  end


  # Loads the project properties for the given projects and returns them in an array.
  # ---------------------------------------------------------------------------------------
  def get_projects_properties(projects)
   properties = []

   projects.each do |project|
    properties.push(get_project_properties(project))
   end

   return properties
  end


  # Loads the project properties for the given projects and returns them in an array.
  # ---------------------------------------------------------------------------------------
  def get_project_properties(project)

    # Make sure that we do have a directory in the proper format and can write into it.
    raise 'There was no directory given.' unless project.directory
    raise 'The directory does not exist.' unless File.directory?(project.directory)
    raise 'Can not write in the directory.' unless File.writable?(project.directory)

    # Does a configuration file in the project's directory still exists?
    unless File.readable?(project.directory + '.i18n-web-organizer') then

      # Oops... OK, we have to create an entry for this project anyway,
      # but we can only write placeholder informations now.
      return {
          :name => '(Unknown)',
          :default_language => '',
          :languages => []
      }

    end

    # OK, open and read the file.
    file_properties = YAML.load_file(project.directory + '.i18n-web-organizer')

    return {
        :name => file_properties[:name],
        :default_language => file_properties[:default_language],
        :languages => file_properties[:languages]
    }
  end

end

app/helpers/properties_helper.rb
require "yaml"

module PropertiesHelper

  # Writes the configuration file for the given project.
  # ---------------------------------------------------------------------------------------
  def update_config(project, config)
   File.open(project.directory + '.i18n-web-organizer', 'w') do |f|
    YAML.dump(config, f)
   end
  end


end

app/helpers/translations_helper.rb
module TranslationsHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>I18nWebOrganizer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= render 'layouts/components/conditional_js' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/components/_conditional_js.html.erb
<% if controller_name == 'properties' then %>
    <script src="<%= project_properties_path(@project, :js) %>" type="text/javascript"></script>
<% end %>

<% if controller_name == 'translations' then %>
    <script src="<%= project_translations_path(@project, :js) %>" type="text/javascript"></script>
<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    The directory in which your project is stored.<br />
    <%= f.text_field :directory %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <% @current_properties = @project_properties.pop %>
  <tr>
    <td><%= @current_properties[:name] %></td>
    <td><%= link_to 'Properties', project_properties_path(project), :id => 'project_properties-' + project.id.to_s %></td>
    <td><%= link_to 'Translations', project_translations_path(project) %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Attention: You are going to delete only the database entry for this project - This WILL NOT delete any file on your computer. Are you sure that you will delete this project here?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/properties/index.html.erb
<%= form_tag(:controller => "properties", :action => "update", :id => @project) do |f| %>

    <div class="field">
      Name<br/>
      <%=
          text_field_tag(
                  'property[name]',
                  @project_property[:name]
          )
      %>
    </div>
    <div class="field">
      Default language<br/>
      <%=
          localized_language_select(
                  'property',
                  'default_language',
                  [@project_property[:default_language]]
          )
      %>
    </div>
    <div class="actions">
      <%= submit_tag 'Save' %>
    </div>

    <hr/>

    <div class="field">
      Language to add<br/>
      <%=
          localized_language_select(
                  'project_properties',
                  'language'
          )
      %>
      <%=
          button_to_function(
                  'Add language',
                  'add_language()',
                  :id => 'project_properties_language-add'
          )
      %>
   </div>

 <p>Current languages:</p>
 <ul id="project_properties_languages">
   <% if @project_property[:languages] then %>
     <% @project_property[:languages].each do |language| %>
       <li><%= language %></li>
     <% end %>
   <% else %>
     <p>There are currently no such languages defined.</p>
   <% end %>
 </ul>


<% end %>

app/views/properties/index.js.erb
// Adds a new language.
// ---------------------------------------------------------------------------------------
function add_language() {

    $.post(
            "<%= update_project_properties_path(@project.id, :json) %>",
            {
                'language': document.getElementById("project_properties_language").value
            },
            function (data) {

                if (!data) {
                    alert("Oops... A server error is occured. Please try it again later.");
                    return;
                }

                if (data[0] == "200") {

                    $('#project_properties_languages').append('<li id="project_properties_language-' + document.getElementById("project_properties_language").value + '">' + document.getElementById("project_properties_language").value + '</li>');

                } else {
                    alert("Oops... The server send an invalid response. The message was NOT sent. Please try it again later.");
                }
            }
    );

}

app/views/translations/index.html.erb
<h2 id="translations_path-current"><%= @translation_config[:current_path] %></h2>
<%=
    select(
            "translations",
            'path',
            options_for_select(@translation_config[:available_paths], @translation_config[:current_path]),
            :id => 'translations_path'
    )
%>
<%=
    button_to_function(
            'Change',
            'load_translation_data()',
            :id => 'translations_path-change'
    )
%>

app/views/translations/index.js.erb
// Loads the new translation data for the given configuration.
// ---------------------------------------------------------------------------------------
function load_translation_data() {

    $.post(
            "<%= load_project_translations_path(@project.id, :json) %>",
            {
                'directory': document.getElementById("translations_path").value
            },
            function (data) {

                if (!data) {
                    alert("Oops... A server error is occured. Please try it again later.");
                    return;
                }

                if (data[0] == "200") {
                    update_data(data);
                } else {
                    alert("Oops... The server send an invalid response. The message was NOT sent. Please try it again later.");
                }
            }
    );

}


// Updates the view with the new translation data.
// ---------------------------------------------------------------------------------------
function update_data(data) {

    // Create variables for readability.
    var data_project_directory = data[1][0];

    // Update the header
    $('#translations_path-current').text(data_project_directory);
}